### ISSUE TITLE
Inactive project

### ISSUE THREAD

**Issue by The3dit0r** [BlueG15/battleshipv2#2]
Greetings, Blue!

I hope this issue finds you well. I've noticed that our project on GitHub has been inactive for a while, and I wanted to reach out to see if you're still interested in continuing our collaboration on it.
I know times are quite tuff, and you have been quite busy recently with school, but I would really like to extend this collaboration with you on the project, hope you haven't given this up yet.

Would love to hear from you soon! Good luck with your study and career ahead.

Sincerely,
December

**Comment by BlueG15** [comment]
issue solved
